// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHUOHR9r00aMFS3gxkAP0TbNVg45RO7q8',
    appId: '1:1071161823591:web:07a5ecbd16288118b21fc2',
    messagingSenderId: '1071161823591',
    projectId: 'cohort-1-squad-bolan',
    authDomain: 'cohort-1-squad-bolan.firebaseapp.com',
    storageBucket: 'cohort-1-squad-bolan.firebasestorage.app',
    measurementId: 'G-2ZDWZ4RZ3L',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEFqA5Nf9SrGs11CVnj74cfzNXyn9r3Pg',
    appId: '1:1071161823591:ios:a1f85c65dc5f44e4b21fc2',
    messagingSenderId: '1071161823591',
    projectId: 'cohort-1-squad-bolan',
    storageBucket: 'cohort-1-squad-bolan.firebasestorage.app',
    iosBundleId: 'com.squadbolan.hisaabaiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEFqA5Nf9SrGs11CVnj74cfzNXyn9r3Pg',
    appId: '1:1071161823591:ios:a1f85c65dc5f44e4b21fc2',
    messagingSenderId: '1071161823591',
    projectId: 'cohort-1-squad-bolan',
    storageBucket: 'cohort-1-squad-bolan.firebasestorage.app',
    iosBundleId: 'com.squadbolan.hisaabaiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHUOHR9r00aMFS3gxkAP0TbNVg45RO7q8',
    appId: '1:1071161823591:web:ac91f68a19f19c78b21fc2',
    messagingSenderId: '1071161823591',
    projectId: 'cohort-1-squad-bolan',
    authDomain: 'cohort-1-squad-bolan.firebaseapp.com',
    storageBucket: 'cohort-1-squad-bolan.firebasestorage.app',
    measurementId: 'G-GYFDXV9H52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJCstEMM_0MZ4IwaSF99H4JqCrUc9o5gc',
    appId: '1:1071161823591:android:e29936bec8422d21b21fc2',
    messagingSenderId: '1071161823591',
    projectId: 'cohort-1-squad-bolan',
    storageBucket: 'cohort-1-squad-bolan.firebasestorage.app',
  );
}
